// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "hero/v1alpha/hero.proto" (package "hero.v1alpha", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message hero.v1alpha.GetHeroRequest
 */
export interface GetHeroRequest {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
}
/**
 * @generated from protobuf message hero.v1alpha.GetAllHeroesResponse
 */
export interface GetAllHeroesResponse {
    /**
     * @generated from protobuf field: repeated hero.v1alpha.Hero heroes = 1;
     */
    heroes: Hero[];
}
/**
 * @generated from protobuf message hero.v1alpha.GetHeroResponse
 */
export interface GetHeroResponse {
    /**
     * @generated from protobuf field: hero.v1alpha.Hero hero = 1;
     */
    hero?: Hero;
}
/**
 * @generated from protobuf message hero.v1alpha.CreateHeroRequest
 */
export interface CreateHeroRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: int32 power = 2;
     */
    power: number;
}
/**
 * @generated from protobuf message hero.v1alpha.Hero
 */
export interface Hero {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: int32 power = 3;
     */
    power: number;
    /**
     * @generated from protobuf field: int32 hp = 4;
     */
    hp: number;
}
/**
 * @generated from protobuf message hero.v1alpha.CreateHeroResponse
 */
export interface CreateHeroResponse {
    /**
     * @generated from protobuf field: hero.v1alpha.Hero hero = 1;
     */
    hero?: Hero;
}
/**
 * @generated from protobuf message hero.v1alpha.DelteHeroRequest
 */
export interface DelteHeroRequest {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
}
/**
 * @generated from protobuf message hero.v1alpha.DelteHeroResponse
 */
export interface DelteHeroResponse {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
/**
 * @generated from protobuf message hero.v1alpha.PutHeroRequest
 */
export interface PutHeroRequest {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: int32 power = 3;
     */
    power: number;
    /**
     * @generated from protobuf field: int32 hp = 4;
     */
    hp: number;
}
/**
 * @generated from protobuf message hero.v1alpha.PutHeroResponse
 */
export interface PutHeroResponse {
    /**
     * @generated from protobuf field: hero.v1alpha.Hero hero = 1;
     */
    hero?: Hero;
}
/**
 * @generated from protobuf message hero.v1alpha.AttackHeroRequest
 */
export interface AttackHeroRequest {
    /**
     * @generated from protobuf field: int32 strikerId = 1;
     */
    strikerId: number;
    /**
     * @generated from protobuf field: int32 defenderId = 2;
     */
    defenderId: number;
}
/**
 * @generated from protobuf message hero.v1alpha.AttackHeroResponse
 */
export interface AttackHeroResponse {
    /**
     * @generated from protobuf field: hero.v1alpha.Hero defender = 1;
     */
    defender?: Hero;
    /**
     * @generated from protobuf field: hero.v1alpha.Hero striker = 2;
     */
    striker?: Hero;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetHeroRequest$Type extends MessageType<GetHeroRequest> {
    constructor() {
        super("hero.v1alpha.GetHeroRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetHeroRequest>): GetHeroRequest {
        const message = { id: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetHeroRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetHeroRequest): GetHeroRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetHeroRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.GetHeroRequest
 */
export const GetHeroRequest = new GetHeroRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllHeroesResponse$Type extends MessageType<GetAllHeroesResponse> {
    constructor() {
        super("hero.v1alpha.GetAllHeroesResponse", [
            { no: 1, name: "heroes", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Hero }
        ]);
    }
    create(value?: PartialMessage<GetAllHeroesResponse>): GetAllHeroesResponse {
        const message = { heroes: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetAllHeroesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllHeroesResponse): GetAllHeroesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated hero.v1alpha.Hero heroes */ 1:
                    message.heroes.push(Hero.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllHeroesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated hero.v1alpha.Hero heroes = 1; */
        for (let i = 0; i < message.heroes.length; i++)
            Hero.internalBinaryWrite(message.heroes[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.GetAllHeroesResponse
 */
export const GetAllHeroesResponse = new GetAllHeroesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetHeroResponse$Type extends MessageType<GetHeroResponse> {
    constructor() {
        super("hero.v1alpha.GetHeroResponse", [
            { no: 1, name: "hero", kind: "message", T: () => Hero }
        ]);
    }
    create(value?: PartialMessage<GetHeroResponse>): GetHeroResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetHeroResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetHeroResponse): GetHeroResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* hero.v1alpha.Hero hero */ 1:
                    message.hero = Hero.internalBinaryRead(reader, reader.uint32(), options, message.hero);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetHeroResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* hero.v1alpha.Hero hero = 1; */
        if (message.hero)
            Hero.internalBinaryWrite(message.hero, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.GetHeroResponse
 */
export const GetHeroResponse = new GetHeroResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateHeroRequest$Type extends MessageType<CreateHeroRequest> {
    constructor() {
        super("hero.v1alpha.CreateHeroRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "power", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CreateHeroRequest>): CreateHeroRequest {
        const message = { name: "", power: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreateHeroRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateHeroRequest): CreateHeroRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* int32 power */ 2:
                    message.power = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateHeroRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* int32 power = 2; */
        if (message.power !== 0)
            writer.tag(2, WireType.Varint).int32(message.power);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.CreateHeroRequest
 */
export const CreateHeroRequest = new CreateHeroRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Hero$Type extends MessageType<Hero> {
    constructor() {
        super("hero.v1alpha.Hero", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "power", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "hp", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Hero>): Hero {
        const message = { id: 0, name: "", power: 0, hp: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Hero>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Hero): Hero {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 power */ 3:
                    message.power = reader.int32();
                    break;
                case /* int32 hp */ 4:
                    message.hp = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Hero, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 power = 3; */
        if (message.power !== 0)
            writer.tag(3, WireType.Varint).int32(message.power);
        /* int32 hp = 4; */
        if (message.hp !== 0)
            writer.tag(4, WireType.Varint).int32(message.hp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.Hero
 */
export const Hero = new Hero$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateHeroResponse$Type extends MessageType<CreateHeroResponse> {
    constructor() {
        super("hero.v1alpha.CreateHeroResponse", [
            { no: 1, name: "hero", kind: "message", T: () => Hero }
        ]);
    }
    create(value?: PartialMessage<CreateHeroResponse>): CreateHeroResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreateHeroResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateHeroResponse): CreateHeroResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* hero.v1alpha.Hero hero */ 1:
                    message.hero = Hero.internalBinaryRead(reader, reader.uint32(), options, message.hero);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateHeroResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* hero.v1alpha.Hero hero = 1; */
        if (message.hero)
            Hero.internalBinaryWrite(message.hero, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.CreateHeroResponse
 */
export const CreateHeroResponse = new CreateHeroResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DelteHeroRequest$Type extends MessageType<DelteHeroRequest> {
    constructor() {
        super("hero.v1alpha.DelteHeroRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<DelteHeroRequest>): DelteHeroRequest {
        const message = { id: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DelteHeroRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DelteHeroRequest): DelteHeroRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DelteHeroRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.DelteHeroRequest
 */
export const DelteHeroRequest = new DelteHeroRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DelteHeroResponse$Type extends MessageType<DelteHeroResponse> {
    constructor() {
        super("hero.v1alpha.DelteHeroResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DelteHeroResponse>): DelteHeroResponse {
        const message = { message: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DelteHeroResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DelteHeroResponse): DelteHeroResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DelteHeroResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.DelteHeroResponse
 */
export const DelteHeroResponse = new DelteHeroResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutHeroRequest$Type extends MessageType<PutHeroRequest> {
    constructor() {
        super("hero.v1alpha.PutHeroRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "power", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "hp", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<PutHeroRequest>): PutHeroRequest {
        const message = { id: 0, name: "", power: 0, hp: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PutHeroRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutHeroRequest): PutHeroRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 power */ 3:
                    message.power = reader.int32();
                    break;
                case /* int32 hp */ 4:
                    message.hp = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutHeroRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 power = 3; */
        if (message.power !== 0)
            writer.tag(3, WireType.Varint).int32(message.power);
        /* int32 hp = 4; */
        if (message.hp !== 0)
            writer.tag(4, WireType.Varint).int32(message.hp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.PutHeroRequest
 */
export const PutHeroRequest = new PutHeroRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutHeroResponse$Type extends MessageType<PutHeroResponse> {
    constructor() {
        super("hero.v1alpha.PutHeroResponse", [
            { no: 1, name: "hero", kind: "message", T: () => Hero }
        ]);
    }
    create(value?: PartialMessage<PutHeroResponse>): PutHeroResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PutHeroResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutHeroResponse): PutHeroResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* hero.v1alpha.Hero hero */ 1:
                    message.hero = Hero.internalBinaryRead(reader, reader.uint32(), options, message.hero);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutHeroResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* hero.v1alpha.Hero hero = 1; */
        if (message.hero)
            Hero.internalBinaryWrite(message.hero, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.PutHeroResponse
 */
export const PutHeroResponse = new PutHeroResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AttackHeroRequest$Type extends MessageType<AttackHeroRequest> {
    constructor() {
        super("hero.v1alpha.AttackHeroRequest", [
            { no: 1, name: "strikerId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "defenderId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<AttackHeroRequest>): AttackHeroRequest {
        const message = { strikerId: 0, defenderId: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AttackHeroRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AttackHeroRequest): AttackHeroRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 strikerId */ 1:
                    message.strikerId = reader.int32();
                    break;
                case /* int32 defenderId */ 2:
                    message.defenderId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AttackHeroRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 strikerId = 1; */
        if (message.strikerId !== 0)
            writer.tag(1, WireType.Varint).int32(message.strikerId);
        /* int32 defenderId = 2; */
        if (message.defenderId !== 0)
            writer.tag(2, WireType.Varint).int32(message.defenderId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.AttackHeroRequest
 */
export const AttackHeroRequest = new AttackHeroRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AttackHeroResponse$Type extends MessageType<AttackHeroResponse> {
    constructor() {
        super("hero.v1alpha.AttackHeroResponse", [
            { no: 1, name: "defender", kind: "message", T: () => Hero },
            { no: 2, name: "striker", kind: "message", T: () => Hero }
        ]);
    }
    create(value?: PartialMessage<AttackHeroResponse>): AttackHeroResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AttackHeroResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AttackHeroResponse): AttackHeroResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* hero.v1alpha.Hero defender */ 1:
                    message.defender = Hero.internalBinaryRead(reader, reader.uint32(), options, message.defender);
                    break;
                case /* hero.v1alpha.Hero striker */ 2:
                    message.striker = Hero.internalBinaryRead(reader, reader.uint32(), options, message.striker);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AttackHeroResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* hero.v1alpha.Hero defender = 1; */
        if (message.defender)
            Hero.internalBinaryWrite(message.defender, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* hero.v1alpha.Hero striker = 2; */
        if (message.striker)
            Hero.internalBinaryWrite(message.striker, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hero.v1alpha.AttackHeroResponse
 */
export const AttackHeroResponse = new AttackHeroResponse$Type();
/**
 * @generated ServiceType for protobuf service hero.v1alpha.HeroService
 */
export const HeroService = new ServiceType("hero.v1alpha.HeroService", [
    { name: "GetHero", options: {}, I: GetHeroRequest, O: GetHeroResponse },
    { name: "CreateHero", options: {}, I: CreateHeroRequest, O: CreateHeroResponse },
    { name: "DeleteHero", options: {}, I: DelteHeroRequest, O: DelteHeroResponse },
    { name: "PutHero", options: {}, I: PutHeroRequest, O: PutHeroResponse },
    { name: "AttackHero", options: {}, I: AttackHeroRequest, O: AttackHeroResponse }
]);
